- name: set sessions directory
  set_fact:
    sessions_dir: '/home/sessions'
    powervc_rc:   '/opt/ibm/powervc/powervcrc'

- name: execute role
  block:
    - fail: msg="<session_id> value is not set, will not proceed"
      when: not session_id

    - name: create session directory
      tempfile: state=directory path="{{sessions_dir}}" prefix='miq_image_import_' suffix=".{{session_id}}"
      register: session_dir

    - name: execute PVC image export to FS
      shell: source {{powervc_rc}} && powervc-image export -i "{{image_id}}" -p "{{session_dir.path}}/{{session_id}}.ova"

    - name: copy the image 'upload.py' python script
      copy: src=files/upload_ova_to_bucket.py dest="{{session_dir.path}}/upload_ova_to_bucket.py" mode=700

    - name: copy the encrypted credentials file
      template: src=templates/credentials.aes dest="{{session_dir.path}}/credentials.aes" mode=700

    - name: execute OVA to COS bucket upload script
      shell: source {{sessions_dir}}/venv/bin/activate && python3.6 "{{session_dir.path}}/upload_ova_to_bucket.py" "{{session_dir.path}}/{{session_id}}.ova"
      environment:
        CREDS_AES_KEY: "{{creds_aes_key}}"
        CREDS_AES_IV:  "{{creds_aes_iv}}"
  always:
    - name: perform cleanup
      file: state=absent path="{{session_dir.path}}"
      when: session_dir is defined